#!/bin/bash
#
# Authors:
# Based on Olena Mokshyna's script.
# Aleksandra Ivanova
# Date : 20.02.2022
#
# Description: The following script prepares ligand and protein input files
#               for energy minization and further simulation;
#               defines the unite cell and fills it with water
#               and adds ions. And runs the final simulation
#
# in case of GROMOS FF - We will make use of two files that PRODRG gives us.
#Save the output of the field "The GROMOS87/GROMACS coordinate file (polar/aromatic hydrogens)"
#
# Run Information: You should prepare input files beforehand: Protonate, add all hydrogens for both, ligand and protein, and complete missing atoms and residues for the protein.
#                  You will need *pdb for ligand (After docking or from crystallographic structure);
#                  *pdb file for the protein;
#                  and *mdp files for each minimization, equalibration and simulation
# Arguments: lfile - *mol or *gro file of ligand,
#            pfile - *pdb or *gro file of protein,
#            mdtime - time in ns
#            script_path - dir contains *.mdp files (ions.mdp, minim.mdp, npt.mdp, nvt.mdp, md.mdp).
#
#
#            Additional arguments:
#            wdir - working dir. Can be skipped. This argument can be skipped, if so current directory will be used.
#
# Example call: qsub -v lfile=lig.mol,pfile=protein.pdb,cfrfile=cofactor.mol,script_path=path,mdtime=5 01_complex_preparation.pbs
# wdir=$(pwd)
#

#PBS -l select=1:ncpus=128:ompthreads=2
#PBS -k oe

>&2 echo 'Script running:***************************** System Variable setting *********************************'

if [ -z $gromacs_version ];
 then
  gromacs_version="GROMACS/2021.4-foss-2020b-PLUMED-2.7.3"
fi

source activate gmxMMPBSA


# allows relative paths
cd $PBS_O_WORKDIR

>&2 echo 'Script running:***************************** 1. Variable setting *********************************'

if [ -z $lfile ];
  then
  >&2 echo 'lfile is not set. Script will be interrupted'
  exit 1
fi

if [ -z $cfrfile ];
  then
  >&2 echo 'cfrfile is not set. Script will be interrupted'
  exit 1
fi

if [ -z $pfile ];
  then
  >&2 echo 'pfile argument is not set. Script will be interrupted'
  exit 1
fi

if [ -z $mdtime ];
  then
  >&2 echo 'mdtime argument is not set. Script will be interrupted'
  exit 1
fi

if [ -z $script_path ];
  then
  >&2 echo 'script_path argument is not set. Script will be interrupted'
  exit 1
fi

if [ -z $wdir ];
  then wdir=$PBS_O_WORKDIR
fi

if [ $script_path == $wdir ]
then
  >&2 echo 'Script error: Working directory equals script path. To avoid *.mdp files be modified current script will be interrupted.'
  exit 1
fi

LNAME="$(awk -F'/' '{print $NF}' <<<$lfile | cut -d'.' -f1)"
PNAME="$(awk -F'/' '{print $NF}' <<<$pfile | cut -d'.' -f1)"

#cofactor file
CFRNAME="$(awk -F'/' '{print $NF}' <<<$cfrfile | cut -d'.' -f1)"

>&2 echo "GROMACS Version:" $gromacs_version
>&2 echo "Ligand:" $LNAME $lfile
>&2 echo "Cofactor:" $CNAME $cfrfile
>&2 echo "Protein:" $PNAME $pfile
>&2 echo "WORKDIR:" $wdir $(pwd)
>&2 echo "Script Path" $script_path
>&2 echo "MDtime:" $mdtime "ns"

mkdir -p $wdir

cd $wdir

# Will Change mdp files
cp $script_path"/"*.mdp .

#ligand prep
>&2 echo 'Script running:***************************** 2.1 Ligand preparation *********************************'
## Using new version of gmx change python version so first need to run amber to prepare ligand and then load the new gmx
if [ $(awk -F'/' '{print $NF}' <<<$lfile |  awk -F. '{print $NF}') != gro ]
 then
  #prepare tleap - add ff from relevant conda env path
  cp $script_path"/tleap.in" .
  sed -i "1s/.*/source "$(echo $CONDA_PREFIX | sed 's/\//\\\//g')"\/dat\/leap\/cmd\/leaprc\.gaff/" tleap.in
  if [ $(awk -F'/' '{print $NF}' <<<$lfile |  awk -F. '{print $NF}') != mol2 ]
  then
   charge=$( python $script_path"/"getcharge.py -i $lfile)
   antechamber -i $lfile -fi mdl -o ligand.mol2 -fo mol2 -c bcc -pf y -s 2 -nc $charge -rn "UNL"
  else
   cp $lfile ligand.mol2
   >&2 echo 'Script running: Using prepared ligand *.mol2 file'
  fi
  parmchk2 -i ligand.mol2 -f mol2 -o ligand.frcmod
  tleap -f tleap.in
  python $script_path"/"pmed_amb2gmx.py -p ligand.prmtop -x ligand.inpcrd -o ligand
 else
#put into dir
  input_dirname=${lfile%/*}"
  cp $input_dirname\/$LNAME.gro ligand.gro
  cp $input_dirname\/$LNAME.top ligand.top
  >&2 echo 'Script running: Using prepared ligand *.gro file'
fi
>&2 echo 'Script running:***************************** 2.2 Cofactor preparation *********************************'
if [ $(awk -F'/' '{print $NF}' <<<$cfrfile |  awk -F. '{print $NF}') != gro ]
 then
  cp $script_path"/tleap.in" tleap_cofactor.in
  sed -i "1s/.*/source "$(echo $CONDA_PREFIX | sed 's/\//\\\//g')"\/dat\/leap\/cmd\/leaprc\.gaff/" tleap_cofactor.in
  sed -i 's/ligand/cofactor/g' tleap_cofactor.in
  
  charge_cfr=$( python $script_path"/"getcharge.py -i $cfrfile)
  antechamber -i $cfrfile -fi mdl -o cofactor.mol2 -fo mol2 -c bcc -pf y -s 2 -nc $charge_cfr -rn "CFR"
  parmchk2 -i cofactor.mol2 -f mol2 -o cofactor.frcmod
  tleap -f tleap_cofactor.in
  python $script_path"/"pmed_amb2gmx.py -p cofactor.prmtop -x cofactor.inpcrd -o cofactor
 else
  input_dirname=${cfrfile%/*}"
  cp $input_dirname\/$CFRNAME.gro cofactor.gro
  cp $input_dirname\/$CFRNAME.top cofactor.top
  >&2 echo 'Script running: Using prepared cofactor *.gro file'
fi

# make new all.itp
cp ligand.top ligand.itp
cp cofactor.top cofactor.itp
## combine [atomtypes] from ligand.itp and cofactor.itp
{ sed -n -e '/atomtypes/,+1 p' ligand.itp && { { sed -n -e '/atomtypes/,/moleculetype/ p' ligand.itp | head -n-3 |tail -n +3 && sed -n -e '/atomtypes/,/moleculetype/ p' cofactor.itp | head -n-3 |tail -n +3  ; } | sort | uniq ; } ;} > all.itp

## remove atomtypes fields from *.itp
sed -ni -e '/atomtypes/,/moleculetype/d; p' ligand.itp
## add [moleculetype] name of field which we have removed the last step
sed -i  "/\; Name            nrexcl/i\[ moleculetype ]" ligand.itp

sed -ni -e '/atomtypes/,/moleculetype/d; p' cofactor.itp
sed -i  "/\; Name            nrexcl/i\[ moleculetype ]" cofactor.itp

# target preparation
>&2 echo 'Script running:***************************** 3. Target preparation *********************************'
>&2 echo 'Start time:' $(date +%H:%M:%S' '%d-%m-%Y)

module load $gromacs_version

if [ $(cut -d '/' -f2 <<<$pfile | cut -d'.' -f2) != gro ]
then
   gmx pdb2gmx -f $pfile -o $PNAME.gro -water tip3p -ignh <<< 6 #pass FF - here AMBER99SB-ILDN
else
   >&2 echo 'Script running: Using prepared protein *.gro file'
fi

# 2.5 Ligand preparation
#create itps

sed -i '/system/,+2 d' ligand.itp
sed -i '/molecules/,+2 d' ligand.itp
sed -i '/defaults/,+2 d' ligand.itp

sed -i '/system/,+2 d' cofactor.itp
sed -i '/molecules/,+2 d' cofactor.itp
sed -i '/defaults/,+2 d' cofactor.itp

# restraints
gmx genrestr -f ligand.gro -o posre_ligand.itp -fc 1000 1000 1000 <<< 2
gmx genrestr -f cofactor.gro -o posre_cofactor.itp -fc 1000 1000 1000 <<< 2
sed -i  "/\; Include topology for ions/i\; Ligand position restraints\n#ifdef POSRES_LIG\n#include \posre_ligand.itp\\n#endif\n" topol.top
sed -i "/\; Include topology for ions/i\; Ligand position restraints\n#ifdef POSRES_CFR\n#include \"posre_cofactor.itp\"\n#endif\n" topol.top


# complex
>&2 echo 'Script running:***************************** 4. Complex preparation *********************************'
#{ head -2 ligand.gro && tail -n+3 $PNAME.gro; } > tmp

cp ligand.gro tmp.gro
sed -i '1,2d' tmp.gro #remove first two
sed -i '$ d' tmp.gro #and last line of gro file (containing?)

cp cofactor.gro tmp2.gro
sed -i '1,2d' tmp2.gro
sed -i '$ d' tmp2.gro

{ head -n-1 $PNAME.gro && cat tmp.gro && tail -n1 $PNAME.gro; } > tmp #insert ligand.gro into complex.gro
{ head -n-1 tmp && cat tmp2.gro && tail -n1 tmp; } > complex.gro #insert cofactor.gro into complex.gro

#THIS STEP IS VERY IMPORTANT! If something goes wrong here there will be bunch of errors later
L_NATOMS=$(head -2 ligand.gro | tail -1)
CFR_NATOMS=$(head -2 cofactor.gro | tail -1)
C_NATOMS=$(($(head -2 complex.gro | tail -1) + $L_NATOMS + $CFR_NATOMS)) #get general number of atoms in complex

sed -i '2s/.*/'"$C_NATOMS"'/' complex.gro #substitute second line with general num of atoms

#Another IMPORTANT step - be sure to check that *itp is not included in the wrong part
# add *.itp to topol.top !Note: the order is important: 1) all.itp 2)ligand.itp 3)cofactor.itp
sed -i '/\; Include forcefield parameters/{N;N;s/$/\n; Include cofactor topology\n#include \"cofactor\.itp\"\n/}' topol.top
sed -i '/\; Include forcefield parameters/{N;N;s/$/\n; Include ligand topology\n#include \"ligand\.itp\"\n/}' topol.top
sed -i '/\; Include forcefield parameters/{N;N;s/$/\n; Include all topology\n#include \"all\.itp\"\n/}' topol.top

#Add ligand to the [ molecules ] directive.
#LNAME_gro=$(head -1 tmp.gro | awk '{print $1;}' |  cut -c2-) #extract ligand name from $LNAME.gro; usually name looks like 1JZ4 - you need to remove first number
LNAME_gro="UNL"
CFRNAME_gro="CFR"
echo "$LNAME_gro"'             1' >> topol.top #and insert ligand and number of ligand molecules into the last line of topol.top
echo "$CFRNAME_gro"'             1' >> topol.top #and insert ligand and number of ligand molecules into the last line of topol.top

# need to check! only CHARMM FF
#if FF provides any other files (i.e. *prm file for CHARMM FF) it should be included at the TOP of topol.top
#before [moleculetype] section
if [ -e ligand.prm ]
  then
    sed -i "/\moleculetype/i\; Include ligand parameters\n#include \"ligand\.prm\"\n" topol.top
  else
    >&2 echo "Script running: No ligand.prm file was provided, so nothing was included in topol.top"
fi

if [ -e cofactor.prm ]
  then
    sed -i "/\moleculetype/i\; Include cofactor parameters\n#include \"cofactor\.prm\"\n" topol.top
  else
    >&2 echo "Script running: No cofactor.prm file was provided, so nothing was included in topol.top"
fi


# Change ligand name in *mdp file (coupling groups).
## tc-grps  = Protein_UNL Water_and_ions; two coupling groups - more accurate
sed -i 's/tc-grps..*/tc-grps                 = Protein_'$LNAME_gro'_'$CFRNAME_gro' Water_and_ions; two coupling groups/' *.mdp
# Change MD simulation time
##nsteps                  = 5000000    ; 2 * 5000000 = 10000000 fs = 10000 ps (10 ns), 25000000*2 fs = 50 ns 100000000
mdsteps=$(awk "BEGIN {picoseconds=$mdtime*1000; femtoseconds=picoseconds*1000; steps=femtoseconds/2; print steps}")
sed -i 's/nsteps..*/nsteps                  = '$mdsteps'        ;/' md.mdp


#Solvate
>&2 echo 'Script running:***************************** 5. Solvation step *********************************'
gmx editconf -f complex.gro -o newbox.gro -c -d 1.0 -bt cubic
#gmx editconf -f complex.gro -o newbox.gro -bt dodecahedron -d 1.2 #Warning about bad box - wrong number of atoms (https://gromacs.org-gmx-users.maillist.sys.kth.narkive.com/q4NXMAoY/bad-box-error) Lena version
gmx solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro


#Add ions
>&2 echo 'Script running:***************************** 6. Ions *********************************'
#use grompp to assemble *tpr file () using any *mdp file
#here one can use *mdp for energy minization (as recommended in Justin's tutorials)
gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr
#-maxwarn 10
#FATAL error SDMSO type not found -> try renaming to SDmso

gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -neutral <<< SOL


# Create group Protein_UNL in index.ndx
>&2 echo 'Script running:***************************** 7. Group indexing *********************************'
index_ligand=$(gmx make_ndx -f solv_ions.gro <<< "q" | sed -rn "s/([0-9]+) "$LNAME_gro"[0-9: ]*atoms/\1/p"| head -1)
>&2 echo 'Ligand Index:' $index_ligand
index_cofactor=$(gmx make_ndx -f solv_ions.gro <<< "q" | sed -rn "s/([0-9]+) "$CFRNAME_gro"[0-9: ]*atoms/\1/p"| head -1)
>&2 echo 'Cofactor Index:' $index_cofactor

gmx make_ndx -f solv_ions.gro -o index.ndx << INPUT
"Protein"|$index_ligand|$index_cofactor
q
INPUT

#Energy minimization
>&2 echo 'Script running:***************************** 8. Energy minimization *********************************'
gmx grompp -f minim.mdp -c solv_ions.gro -p topol.top -n index.ndx -o em.tpr -maxwarn 1
gmx mdrun -v -deffnm em -s em.tpr

##last but not least generate files for further analysis
gmx energy -f em.edr -o potential.xvg <<< "Potential"


# NVT
>&2 echo 'Script running:***************************** 9. NVT *********************************'
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr -maxwarn 1
gmx mdrun -deffnm nvt -s nvt.tpr

gmx energy -f nvt.edr -o temperature.xvg  <<< "Temperature"


# NPT
>&2 echo 'Script running:***************************** 10. NPT *********************************'
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -n index.ndx -o npt.tpr  -maxwarn 1
gmx mdrun -deffnm npt -s npt.tpr

gmx energy -f npt.edr -o pressure.xvg <<< "Pressure"
gmx energy -f npt.edr -o density.xvg <<< "Density"


# MD
>&2 echo 'Script running:***************************** 11. MD simulation *********************************'
>&2 echo 'Run simulation:' $mdtime 'ns'
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -n index.ndx -o md_out.tpr -maxwarn 1
gmx mdrun -deffnm md_out -s md_out.tpr


# RMSD
>&2 echo 'Script running:***************************** 12. MD analysis *********************************'

# ligand without Hs
#UNL_&_!H*
gmx make_ndx -f solv_ions.gro -n index.ndx << INPUT
$index_ligand & ! a H*
q
INPUT

index_ligand_noH=$(gmx make_ndx -f solv_ions.gro -n index.ndx <<< "q" | sed -rn "s/([0-9]+) "$LNAME_gro"_\&_\!H\*[0-9: ]*atoms/\1/p"| head -1)

# set tstep
if (( $mdtime >= 10 ))
then
  tu="ns"
else
  tu="ps"
fi

gmx trjconv -s md_out.tpr -f md_out.xtc -pbc nojump -o md_out_noj_noPBC.xtc <<< "System"
#gmx trjconv -s md_out.tpr -f md_out.xtc -o md_out_noPBC.xtc -pbc mol -center <<< "Protein  System"
gmx trjconv -s md_out.tpr -f md_out_noj_noPBC.xtc -o md_centermolsnoPBC.xtc -pbc mol -center -n index.ndx  <<< "Protein_UNL  System"
gmx trjconv -s md_out.tpr -f md_centermolsnoPBC.xtc -fit rot+trans -o md_fit.xtc  -n index.ndx <<< "Protein_UNL  System"

if (( $mdtime >= 50 ))
then
  dtstep=100
else
  dtstep=50
fi

gmx trjconv -s md_out.tpr -f md_fit.xtc -dt $dtstep -o md_short_forcheck.xtc <<< "System"

gmx rms -s md_out.tpr -f md_fit.xtc -o rmsd.xvg -n index.ndx -tu $tu <<< "Backbone  Backbone"
gmx rms -s em.tpr -f md_fit.xtc -o rmsd_xtal.xvg -n index.ndx -tu $tu <<< "Backbone  Backbone"

gmx rms -s md_out.tpr -f md_fit.xtc -o rmsd_$LNAME_gro\.xvg -n index.ndx  -tu $tu <<< "Backbone  $index_ligand_noH"
gmx rms -s em.tpr -f md_fit.xtc -o rmsd_$LNAME_gro\_xtal.xvg -n index.ndx -tu $tu <<< "Backbone  $index_ligand_noH"

gmx gyrate -s md_out.tpr -f md_fit.xtc -n index.ndx -o gyrate.xvg <<< "Protein"

gmx rmsf -s md_out.tpr -f md_fit.xtc -n index.ndx -o rmsf.xvg -oq rmsf.pdb -res <<< "Protein"

gmx trjconv -s md_out.tpr -f md_fit.xtc -o frame.pdb -b 10 -e 11  -n index.ndx <<< "System"

>&2 echo 'Script running:***************************** FINISH *********************************'
cp ~/$PBS_JOBNAME.{e,o}${PBS_JOBID%.*} .
